#!/bin/bash

# get
# post usuari passwd

test -f $(dirname $0)/build/index.cgi || exit 1
cd $(dirname $0)/build

# Elimina variables d'entorn importants que no estan definides
# quan el CGI és cridat des del servidor
unset PATH

echo $1

function showvars
{
	# Mostra variables d'entorn
	echo "=================="
	echo "VARIABLES D'ENTORN"
	echo "=================="
	/usr/bin/env | /usr/bin/sort

	echo ""
	echo "==============="
	echo "SORTIDA DEL CGI"
	echo "==============="
}

# Defineix les variables d'entorn usades pel CGI
if test "x$1" = "xget"; then
	export REQUEST_METHOD="GET"
	showvars
	# Invoca el CGI 'index.cgi'
	./index.cgi
elif test "x$1" = "xpost"; then
	export REQUEST_METHOD="POST"
	form="user=$2&passwd=$3&login=$4"
	export REQUEST_METHOD="POST"
	export CONTENT_TYPE="application/x-www-form-urlencoded"
	export CONTENT_LENGTH=$(/usr/bin/expr length $form)
	showvars
	# Invoca el CGI 'index.cgi' passant el contingut del formulari
	# per l'entrada estandar
	echo $form | ./index.cgi
else
	echo "Bad arguments"
	echo 'Usage: [get, post]<post user><post passwd>'
fi


