.TH "beacon_data" 3 "Sun Jun 1 2014" "Version 1.0" "net_mac80211" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beacon_data \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ieee80211_i\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "u8 * \fBhead\fP"
.br
.ti -1c
.RI "u8 * \fBtail\fP"
.br
.ti -1c
.RI "int \fBhead_len\fP"
.br
.ti -1c
.RI "int \fBtail_len\fP"
.br
.ti -1c
.RI "struct rcu_head \fBrcu_head\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 266 of file ieee80211_i\&.h\&.
.SH "Field Documentation"
.PP 
.SS "u8* head"

.PP
Definition at line 267 of file ieee80211_i\&.h\&.
.SS "int head_len"

.PP
Definition at line 268 of file ieee80211_i\&.h\&.
.SS "struct rcu_head rcu_head"

.PP
Definition at line 269 of file ieee80211_i\&.h\&.
.SS "u8 * tail"

.PP
Definition at line 267 of file ieee80211_i\&.h\&.
.SS "int tail_len"

.PP
Definition at line 268 of file ieee80211_i\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for net_mac80211 from the source code\&.
