.TH "/home/guille/msm/net/mac80211/cfg.h" 3 "Sun Jun 1 2014" "Version 1.0" "net_mac80211" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/guille/msm/net/mac80211/cfg.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "struct cfg80211_ops \fBmac80211_config_ops\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "struct cfg80211_ops mac80211_config_ops"

.PP
Definition at line 2678 of file cfg\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for net_mac80211 from the source code\&.
