.TH "/home/guille/msm/net/mac80211/driver-trace.c" 3 "Sun Jun 1 2014" "Version 1.0" "net_mac80211" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/guille/msm/net/mac80211/driver-trace.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <linux/module\&.h>\fP
.br
\fC#include 'driver-ops\&.h'\fP
.br
\fC#include 'driver-trace\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCREATE_TRACE_POINTS\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CREATE_TRACE_POINTS"

.PP
Definition at line 7 of file driver-trace\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for net_mac80211 from the source code\&.
