.TH "/home/guille/msm/net/mac80211/driver-ops.h" 3 "Sun Jun 1 2014" "Version 1.0" "net_mac80211" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/guille/msm/net/mac80211/driver-ops.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <net/mac80211\&.h>\fP
.br
\fC#include 'ieee80211_i\&.h'\fP
.br
\fC#include 'driver-trace\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for net_mac80211 from the source code\&.
