.TH "ieee80211_tx_data" 3 "Sun Jun 1 2014" "Version 1.0" "net_mac80211" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ieee80211_tx_data \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ieee80211_i\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct sk_buff * \fBskb\fP"
.br
.ti -1c
.RI "struct sk_buff_head \fBskbs\fP"
.br
.ti -1c
.RI "struct \fBieee80211_local\fP * \fBlocal\fP"
.br
.ti -1c
.RI "struct \fBieee80211_sub_if_data\fP * \fBsdata\fP"
.br
.ti -1c
.RI "struct \fBsta_info\fP * \fBsta\fP"
.br
.ti -1c
.RI "struct \fBieee80211_key\fP * \fBkey\fP"
.br
.ti -1c
.RI "struct ieee80211_channel * \fBchannel\fP"
.br
.ti -1c
.RI "unsigned int \fBflags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 181 of file ieee80211_i\&.h\&.
.SH "Field Documentation"
.PP 
.SS "struct ieee80211_channel* channel"

.PP
Definition at line 189 of file ieee80211_i\&.h\&.
.SS "unsigned int flags"

.PP
Definition at line 191 of file ieee80211_i\&.h\&.
.SS "struct \fBieee80211_key\fP* key"

.PP
Definition at line 187 of file ieee80211_i\&.h\&.
.SS "struct \fBieee80211_local\fP* local"

.PP
Definition at line 184 of file ieee80211_i\&.h\&.
.SS "struct \fBieee80211_sub_if_data\fP* sdata"

.PP
Definition at line 185 of file ieee80211_i\&.h\&.
.SS "struct sk_buff* skb"

.PP
Definition at line 182 of file ieee80211_i\&.h\&.
.SS "struct sk_buff_head skbs"

.PP
Definition at line 183 of file ieee80211_i\&.h\&.
.SS "struct \fBsta_info\fP* sta"

.PP
Definition at line 186 of file ieee80211_i\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for net_mac80211 from the source code\&.
