.TH "ieee80211_if_vlan" 3 "Sun Jun 1 2014" "Version 1.0" "net_mac80211" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ieee80211_if_vlan \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ieee80211_i\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct list_head \fBlist\fP"
.br
.ti -1c
.RI "struct \fBsta_info\fP __rcu * \fBsta\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 294 of file ieee80211_i\&.h\&.
.SH "Field Documentation"
.PP 
.SS "struct list_head list"

.PP
Definition at line 295 of file ieee80211_i\&.h\&.
.SS "struct \fBsta_info\fP __rcu* sta"

.PP
Definition at line 298 of file ieee80211_i\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for net_mac80211 from the source code\&.
