.TH "ieee80211_ra_tid" 3 "Sun Jun 1 2014" "Version 1.0" "net_mac80211" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ieee80211_ra_tid \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ieee80211_i\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "u8 \fBra\fP [ETH_ALEN]"
.br
.ti -1c
.RI "u16 \fBtid\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1095 of file ieee80211_i\&.h\&.
.SH "Field Documentation"
.PP 
.SS "u8 ra[ETH_ALEN]"

.PP
Definition at line 1096 of file ieee80211_i\&.h\&.
.SS "u16 tid"

.PP
Definition at line 1097 of file ieee80211_i\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for net_mac80211 from the source code\&.
