.TH "ieee80211_if_wds" 3 "Sun Jun 1 2014" "Version 1.0" "net_mac80211" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ieee80211_if_wds \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ieee80211_i\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBsta_info\fP * \fBsta\fP"
.br
.ti -1c
.RI "u8 \fBremote_addr\fP [ETH_ALEN]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 289 of file ieee80211_i\&.h\&.
.SH "Field Documentation"
.PP 
.SS "u8 remote_addr[ETH_ALEN]"

.PP
Definition at line 291 of file ieee80211_i\&.h\&.
.SS "struct \fBsta_info\fP* sta"

.PP
Definition at line 290 of file ieee80211_i\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for net_mac80211 from the source code\&.
