.TH "mcs_group" 3 "Sun Jun 1 2014" "Version 1.0" "net_mac80211" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mcs_group \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rc80211_minstrel_ht\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "u32 \fBflags\fP"
.br
.ti -1c
.RI "unsigned int \fBstreams\fP"
.br
.ti -1c
.RI "unsigned int \fBduration\fP [\fBMCS_GROUP_RATES\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file rc80211_minstrel_ht\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned int duration[\fBMCS_GROUP_RATES\fP]"

.PP
Definition at line 29 of file rc80211_minstrel_ht\&.h\&.
.SS "u32 flags"

.PP
Definition at line 27 of file rc80211_minstrel_ht\&.h\&.
.SS "unsigned int streams"

.PP
Definition at line 28 of file rc80211_minstrel_ht\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for net_mac80211 from the source code\&.
