.TH "mesh_stats" 3 "Sun Jun 1 2014" "Version 1.0" "net_mac80211" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mesh_stats \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ieee80211_i\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "__u32 \fBfwded_mcast\fP"
.br
.ti -1c
.RI "__u32 \fBfwded_unicast\fP"
.br
.ti -1c
.RI "__u32 \fBfwded_frames\fP"
.br
.ti -1c
.RI "__u32 \fBdropped_frames_ttl\fP"
.br
.ti -1c
.RI "__u32 \fBdropped_frames_no_route\fP"
.br
.ti -1c
.RI "__u32 \fBdropped_frames_congestion\fP"
.br
.ti -1c
.RI "atomic_t \fBestab_plinks\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 301 of file ieee80211_i\&.h\&.
.SH "Field Documentation"
.PP 
.SS "__u32 dropped_frames_congestion"

.PP
Definition at line 307 of file ieee80211_i\&.h\&.
.SS "__u32 dropped_frames_no_route"

.PP
Definition at line 306 of file ieee80211_i\&.h\&.
.SS "__u32 dropped_frames_ttl"

.PP
Definition at line 305 of file ieee80211_i\&.h\&.
.SS "atomic_t estab_plinks"

.PP
Definition at line 308 of file ieee80211_i\&.h\&.
.SS "__u32 fwded_frames"

.PP
Definition at line 304 of file ieee80211_i\&.h\&.
.SS "__u32 fwded_mcast"

.PP
Definition at line 302 of file ieee80211_i\&.h\&.
.SS "__u32 fwded_unicast"

.PP
Definition at line 303 of file ieee80211_i\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for net_mac80211 from the source code\&.
