.TH "mesh_rmc" 3 "Sun Jun 1 2014" "Version 1.0" "net_mac80211" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mesh_rmc \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mesh\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBrmc_entry\fP \fBbucket\fP [\fBRMC_BUCKETS\fP]"
.br
.ti -1c
.RI "u32 \fBidx_mask\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 179 of file mesh\&.h\&.
.SH "Field Documentation"
.PP 
.SS "struct \fBrmc_entry\fP bucket[\fBRMC_BUCKETS\fP]"

.PP
Definition at line 180 of file mesh\&.h\&.
.SS "u32 idx_mask"

.PP
Definition at line 181 of file mesh\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for net_mac80211 from the source code\&.
