.TH "michael_mic_ctx" 3 "Sun Jun 1 2014" "Version 1.0" "net_mac80211" \" -*- nroff -*-
.ad l
.nh
.SH NAME
michael_mic_ctx \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <michael\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "u32 \fBl\fP"
.br
.ti -1c
.RI "u32 \fBr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file michael\&.h\&.
.SH "Field Documentation"
.PP 
.SS "u32 l"

.PP
Definition at line 18 of file michael\&.h\&.
.SS "u32 r"

.PP
Definition at line 18 of file michael\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for net_mac80211 from the source code\&.
