.TH "minstrel_mcs_group_data" 3 "Sun Jun 1 2014" "Version 1.0" "net_mac80211" \" -*- nroff -*-
.ad l
.nh
.SH NAME
minstrel_mcs_group_data \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rc80211_minstrel_ht\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "u8 \fBindex\fP"
.br
.ti -1c
.RI "u8 \fBcolumn\fP"
.br
.ti -1c
.RI "u8 \fBsupported\fP"
.br
.ti -1c
.RI "unsigned int \fBmax_tp_rate\fP"
.br
.ti -1c
.RI "unsigned int \fBmax_tp_rate2\fP"
.br
.ti -1c
.RI "unsigned int \fBmax_prob_rate\fP"
.br
.ti -1c
.RI "struct \fBminstrel_rate_stats\fP \fBrates\fP [\fBMCS_GROUP_RATES\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 56 of file rc80211_minstrel_ht\&.h\&.
.SH "Field Documentation"
.PP 
.SS "u8 column"

.PP
Definition at line 58 of file rc80211_minstrel_ht\&.h\&.
.SS "u8 index"

.PP
Definition at line 57 of file rc80211_minstrel_ht\&.h\&.
.SS "unsigned int max_prob_rate"

.PP
Definition at line 66 of file rc80211_minstrel_ht\&.h\&.
.SS "unsigned int max_tp_rate"

.PP
Definition at line 64 of file rc80211_minstrel_ht\&.h\&.
.SS "unsigned int max_tp_rate2"

.PP
Definition at line 65 of file rc80211_minstrel_ht\&.h\&.
.SS "struct \fBminstrel_rate_stats\fP rates[\fBMCS_GROUP_RATES\fP]"

.PP
Definition at line 69 of file rc80211_minstrel_ht\&.h\&.
.SS "u8 supported"

.PP
Definition at line 61 of file rc80211_minstrel_ht\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for net_mac80211 from the source code\&.
