.TH "minstrel_priv" 3 "Sun Jun 1 2014" "Version 1.0" "net_mac80211" \" -*- nroff -*-
.ad l
.nh
.SH NAME
minstrel_priv \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rc80211_minstrel\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct ieee80211_hw * \fBhw\fP"
.br
.ti -1c
.RI "bool \fBhas_mrr\fP"
.br
.ti -1c
.RI "unsigned int \fBcw_min\fP"
.br
.ti -1c
.RI "unsigned int \fBcw_max\fP"
.br
.ti -1c
.RI "unsigned int \fBmax_retry\fP"
.br
.ti -1c
.RI "unsigned int \fBewma_level\fP"
.br
.ti -1c
.RI "unsigned int \fBsegment_size\fP"
.br
.ti -1c
.RI "unsigned int \fBupdate_interval\fP"
.br
.ti -1c
.RI "unsigned int \fBlookaround_rate\fP"
.br
.ti -1c
.RI "unsigned int \fBlookaround_rate_mrr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 70 of file rc80211_minstrel\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned int cw_max"

.PP
Definition at line 74 of file rc80211_minstrel\&.h\&.
.SS "unsigned int cw_min"

.PP
Definition at line 73 of file rc80211_minstrel\&.h\&.
.SS "unsigned int ewma_level"

.PP
Definition at line 76 of file rc80211_minstrel\&.h\&.
.SS "bool has_mrr"

.PP
Definition at line 72 of file rc80211_minstrel\&.h\&.
.SS "struct ieee80211_hw* hw"

.PP
Definition at line 71 of file rc80211_minstrel\&.h\&.
.SS "unsigned int lookaround_rate"

.PP
Definition at line 79 of file rc80211_minstrel\&.h\&.
.SS "unsigned int lookaround_rate_mrr"

.PP
Definition at line 80 of file rc80211_minstrel\&.h\&.
.SS "unsigned int max_retry"

.PP
Definition at line 75 of file rc80211_minstrel\&.h\&.
.SS "unsigned int segment_size"

.PP
Definition at line 77 of file rc80211_minstrel\&.h\&.
.SS "unsigned int update_interval"

.PP
Definition at line 78 of file rc80211_minstrel\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for net_mac80211 from the source code\&.
