.TH "minstrel_ht_sta_priv" 3 "Sun Jun 1 2014" "Version 1.0" "net_mac80211" \" -*- nroff -*-
.ad l
.nh
.SH NAME
minstrel_ht_sta_priv \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rc80211_minstrel_ht\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   struct \fBminstrel_ht_sta\fP \fBht\fP"
.br
.ti -1c
.RI "   struct \fBminstrel_sta_info\fP \fBlegacy\fP"
.br
.ti -1c
.RI "}; "
.br
.ti -1c
.RI "void * \fBratelist\fP"
.br
.ti -1c
.RI "void * \fBsample_table\fP"
.br
.ti -1c
.RI "bool \fBis_ht\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 114 of file rc80211_minstrel_ht\&.h\&.
.SH "Field Documentation"
.PP 
.SS "union { \&.\&.\&. } "

.SS "struct \fBminstrel_ht_sta\fP ht"

.PP
Definition at line 116 of file rc80211_minstrel_ht\&.h\&.
.SS "bool is_ht"

.PP
Definition at line 124 of file rc80211_minstrel_ht\&.h\&.
.SS "struct \fBminstrel_sta_info\fP legacy"

.PP
Definition at line 117 of file rc80211_minstrel_ht\&.h\&.
.SS "void* ratelist"

.PP
Definition at line 122 of file rc80211_minstrel_ht\&.h\&.
.SS "void* sample_table"

.PP
Definition at line 123 of file rc80211_minstrel_ht\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for net_mac80211 from the source code\&.
