.TH "minstrel_rate" 3 "Sun Jun 1 2014" "Version 1.0" "net_mac80211" \" -*- nroff -*-
.ad l
.nh
.SH NAME
minstrel_rate \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rc80211_minstrel\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBbitrate\fP"
.br
.ti -1c
.RI "int \fBrix\fP"
.br
.ti -1c
.RI "unsigned int \fBperfect_tx_time\fP"
.br
.ti -1c
.RI "unsigned int \fBack_time\fP"
.br
.ti -1c
.RI "int \fBsample_limit\fP"
.br
.ti -1c
.RI "unsigned int \fBretry_count\fP"
.br
.ti -1c
.RI "unsigned int \fBretry_count_cts\fP"
.br
.ti -1c
.RI "unsigned int \fBretry_count_rtscts\fP"
.br
.ti -1c
.RI "unsigned int \fBadjusted_retry_count\fP"
.br
.ti -1c
.RI "u32 \fBsuccess\fP"
.br
.ti -1c
.RI "u32 \fBattempts\fP"
.br
.ti -1c
.RI "u32 \fBlast_attempts\fP"
.br
.ti -1c
.RI "u32 \fBlast_success\fP"
.br
.ti -1c
.RI "u32 \fBcur_prob\fP"
.br
.ti -1c
.RI "u32 \fBprobability\fP"
.br
.ti -1c
.RI "u32 \fBcur_tp\fP"
.br
.ti -1c
.RI "u64 \fBsucc_hist\fP"
.br
.ti -1c
.RI "u64 \fBatt_hist\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file rc80211_minstrel\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned int ack_time"

.PP
Definition at line 17 of file rc80211_minstrel\&.h\&.
.SS "unsigned int adjusted_retry_count"

.PP
Definition at line 23 of file rc80211_minstrel\&.h\&.
.SS "u64 att_hist"

.PP
Definition at line 38 of file rc80211_minstrel\&.h\&.
.SS "u32 attempts"

.PP
Definition at line 26 of file rc80211_minstrel\&.h\&.
.SS "int bitrate"

.PP
Definition at line 13 of file rc80211_minstrel\&.h\&.
.SS "u32 cur_prob"

.PP
Definition at line 31 of file rc80211_minstrel\&.h\&.
.SS "u32 cur_tp"

.PP
Definition at line 35 of file rc80211_minstrel\&.h\&.
.SS "u32 last_attempts"

.PP
Definition at line 27 of file rc80211_minstrel\&.h\&.
.SS "u32 last_success"

.PP
Definition at line 28 of file rc80211_minstrel\&.h\&.
.SS "unsigned int perfect_tx_time"

.PP
Definition at line 16 of file rc80211_minstrel\&.h\&.
.SS "u32 probability"

.PP
Definition at line 32 of file rc80211_minstrel\&.h\&.
.SS "unsigned int retry_count"

.PP
Definition at line 20 of file rc80211_minstrel\&.h\&.
.SS "unsigned int retry_count_cts"

.PP
Definition at line 21 of file rc80211_minstrel\&.h\&.
.SS "unsigned int retry_count_rtscts"

.PP
Definition at line 22 of file rc80211_minstrel\&.h\&.
.SS "int rix"

.PP
Definition at line 14 of file rc80211_minstrel\&.h\&.
.SS "int sample_limit"

.PP
Definition at line 19 of file rc80211_minstrel\&.h\&.
.SS "u64 succ_hist"

.PP
Definition at line 37 of file rc80211_minstrel\&.h\&.
.SS "u32 success"

.PP
Definition at line 25 of file rc80211_minstrel\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for net_mac80211 from the source code\&.
