.TH "minstrel_debugfs_info" 3 "Sun Jun 1 2014" "Version 1.0" "net_mac80211" \" -*- nroff -*-
.ad l
.nh
.SH NAME
minstrel_debugfs_info \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rc80211_minstrel\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBlen\fP"
.br
.ti -1c
.RI "char \fBbuf\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 95 of file rc80211_minstrel\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char buf[]"

.PP
Definition at line 97 of file rc80211_minstrel\&.h\&.
.SS "size_t len"

.PP
Definition at line 96 of file rc80211_minstrel\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for net_mac80211 from the source code\&.
