.TH "minstrel_rate_stats" 3 "Sun Jun 1 2014" "Version 1.0" "net_mac80211" \" -*- nroff -*-
.ad l
.nh
.SH NAME
minstrel_rate_stats \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rc80211_minstrel_ht\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBattempts\fP"
.br
.ti -1c
.RI "unsigned int \fBlast_attempts\fP"
.br
.ti -1c
.RI "unsigned int \fBsuccess\fP"
.br
.ti -1c
.RI "unsigned int \fBlast_success\fP"
.br
.ti -1c
.RI "u64 \fBatt_hist\fP"
.br
.ti -1c
.RI "u64 \fBsucc_hist\fP"
.br
.ti -1c
.RI "unsigned int \fBcur_tp\fP"
.br
.ti -1c
.RI "unsigned int \fBcur_prob\fP"
.br
.ti -1c
.RI "unsigned int \fBprobability\fP"
.br
.ti -1c
.RI "unsigned int \fBretry_count\fP"
.br
.ti -1c
.RI "unsigned int \fBretry_count_rtscts\fP"
.br
.ti -1c
.RI "bool \fBretry_updated\fP"
.br
.ti -1c
.RI "u8 \fBsample_skipped\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 34 of file rc80211_minstrel_ht\&.h\&.
.SH "Field Documentation"
.PP 
.SS "u64 att_hist"

.PP
Definition at line 40 of file rc80211_minstrel_ht\&.h\&.
.SS "unsigned int attempts"

.PP
Definition at line 36 of file rc80211_minstrel_ht\&.h\&.
.SS "unsigned int cur_prob"

.PP
Definition at line 46 of file rc80211_minstrel_ht\&.h\&.
.SS "unsigned int cur_tp"

.PP
Definition at line 43 of file rc80211_minstrel_ht\&.h\&.
.SS "unsigned int last_attempts"

.PP
Definition at line 36 of file rc80211_minstrel_ht\&.h\&.
.SS "unsigned int last_success"

.PP
Definition at line 37 of file rc80211_minstrel_ht\&.h\&.
.SS "unsigned int probability"

.PP
Definition at line 46 of file rc80211_minstrel_ht\&.h\&.
.SS "unsigned int retry_count"

.PP
Definition at line 49 of file rc80211_minstrel_ht\&.h\&.
.SS "unsigned int retry_count_rtscts"

.PP
Definition at line 50 of file rc80211_minstrel_ht\&.h\&.
.SS "bool retry_updated"

.PP
Definition at line 52 of file rc80211_minstrel_ht\&.h\&.
.SS "u8 sample_skipped"

.PP
Definition at line 53 of file rc80211_minstrel_ht\&.h\&.
.SS "u64 succ_hist"

.PP
Definition at line 40 of file rc80211_minstrel_ht\&.h\&.
.SS "unsigned int success"

.PP
Definition at line 37 of file rc80211_minstrel_ht\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for net_mac80211 from the source code\&.
