.TH "minstrel_ht_sta" 3 "Sun Jun 1 2014" "Version 1.0" "net_mac80211" \" -*- nroff -*-
.ad l
.nh
.SH NAME
minstrel_ht_sta \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rc80211_minstrel_ht\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBampdu_len\fP"
.br
.ti -1c
.RI "unsigned int \fBampdu_packets\fP"
.br
.ti -1c
.RI "unsigned int \fBavg_ampdu_len\fP"
.br
.ti -1c
.RI "unsigned int \fBmax_tp_rate\fP"
.br
.ti -1c
.RI "unsigned int \fBmax_tp_rate2\fP"
.br
.ti -1c
.RI "unsigned int \fBmax_prob_rate\fP"
.br
.ti -1c
.RI "unsigned long \fBstats_update\fP"
.br
.ti -1c
.RI "unsigned int \fBoverhead\fP"
.br
.ti -1c
.RI "unsigned int \fBoverhead_rtscts\fP"
.br
.ti -1c
.RI "unsigned int \fBtotal_packets\fP"
.br
.ti -1c
.RI "unsigned int \fBsample_packets\fP"
.br
.ti -1c
.RI "u32 \fBtx_flags\fP"
.br
.ti -1c
.RI "u8 \fBsample_wait\fP"
.br
.ti -1c
.RI "u8 \fBsample_tries\fP"
.br
.ti -1c
.RI "u8 \fBsample_count\fP"
.br
.ti -1c
.RI "u8 \fBsample_slow\fP"
.br
.ti -1c
.RI "u8 \fBsample_group\fP"
.br
.ti -1c
.RI "struct \fBminstrel_mcs_group_data\fP \fBgroups\fP [\fBMINSTREL_MAX_STREAMS\fP *\fBMINSTREL_STREAM_GROUPS\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 72 of file rc80211_minstrel_ht\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned int ampdu_len"

.PP
Definition at line 74 of file rc80211_minstrel_ht\&.h\&.
.SS "unsigned int ampdu_packets"

.PP
Definition at line 75 of file rc80211_minstrel_ht\&.h\&.
.SS "unsigned int avg_ampdu_len"

.PP
Definition at line 78 of file rc80211_minstrel_ht\&.h\&.
.SS "struct \fBminstrel_mcs_group_data\fP groups[\fBMINSTREL_MAX_STREAMS\fP *\fBMINSTREL_STREAM_GROUPS\fP]"

.PP
Definition at line 111 of file rc80211_minstrel_ht\&.h\&.
.SS "unsigned int max_prob_rate"

.PP
Definition at line 87 of file rc80211_minstrel_ht\&.h\&.
.SS "unsigned int max_tp_rate"

.PP
Definition at line 81 of file rc80211_minstrel_ht\&.h\&.
.SS "unsigned int max_tp_rate2"

.PP
Definition at line 84 of file rc80211_minstrel_ht\&.h\&.
.SS "unsigned int overhead"

.PP
Definition at line 93 of file rc80211_minstrel_ht\&.h\&.
.SS "unsigned int overhead_rtscts"

.PP
Definition at line 94 of file rc80211_minstrel_ht\&.h\&.
.SS "u8 sample_count"

.PP
Definition at line 104 of file rc80211_minstrel_ht\&.h\&.
.SS "u8 sample_group"

.PP
Definition at line 108 of file rc80211_minstrel_ht\&.h\&.
.SS "unsigned int sample_packets"

.PP
Definition at line 97 of file rc80211_minstrel_ht\&.h\&.
.SS "u8 sample_slow"

.PP
Definition at line 105 of file rc80211_minstrel_ht\&.h\&.
.SS "u8 sample_tries"

.PP
Definition at line 103 of file rc80211_minstrel_ht\&.h\&.
.SS "u8 sample_wait"

.PP
Definition at line 102 of file rc80211_minstrel_ht\&.h\&.
.SS "unsigned long stats_update"

.PP
Definition at line 90 of file rc80211_minstrel_ht\&.h\&.
.SS "unsigned int total_packets"

.PP
Definition at line 96 of file rc80211_minstrel_ht\&.h\&.
.SS "u32 tx_flags"

.PP
Definition at line 100 of file rc80211_minstrel_ht\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for net_mac80211 from the source code\&.
