.TH "minstrel_sta_info" 3 "Sun Jun 1 2014" "Version 1.0" "net_mac80211" \" -*- nroff -*-
.ad l
.nh
.SH NAME
minstrel_sta_info \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rc80211_minstrel\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned long \fBstats_update\fP"
.br
.ti -1c
.RI "unsigned int \fBsp_ack_dur\fP"
.br
.ti -1c
.RI "unsigned int \fBrate_avg\fP"
.br
.ti -1c
.RI "unsigned int \fBlowest_rix\fP"
.br
.ti -1c
.RI "unsigned int \fBmax_tp_rate\fP"
.br
.ti -1c
.RI "unsigned int \fBmax_tp_rate2\fP"
.br
.ti -1c
.RI "unsigned int \fBmax_prob_rate\fP"
.br
.ti -1c
.RI "unsigned int \fBpacket_count\fP"
.br
.ti -1c
.RI "unsigned int \fBsample_count\fP"
.br
.ti -1c
.RI "int \fBsample_deferred\fP"
.br
.ti -1c
.RI "unsigned int \fBsample_idx\fP"
.br
.ti -1c
.RI "unsigned int \fBsample_column\fP"
.br
.ti -1c
.RI "int \fBn_rates\fP"
.br
.ti -1c
.RI "struct \fBminstrel_rate\fP * \fBr\fP"
.br
.ti -1c
.RI "bool \fBprev_sample\fP"
.br
.ti -1c
.RI "u8 * \fBsample_table\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 41 of file rc80211_minstrel\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned int lowest_rix"

.PP
Definition at line 46 of file rc80211_minstrel\&.h\&.
.SS "unsigned int max_prob_rate"

.PP
Definition at line 50 of file rc80211_minstrel\&.h\&.
.SS "unsigned int max_tp_rate"

.PP
Definition at line 48 of file rc80211_minstrel\&.h\&.
.SS "unsigned int max_tp_rate2"

.PP
Definition at line 49 of file rc80211_minstrel\&.h\&.
.SS "int n_rates"

.PP
Definition at line 58 of file rc80211_minstrel\&.h\&.
.SS "unsigned int packet_count"

.PP
Definition at line 51 of file rc80211_minstrel\&.h\&.
.SS "bool prev_sample"

.PP
Definition at line 60 of file rc80211_minstrel\&.h\&.
.SS "struct \fBminstrel_rate\fP* r"

.PP
Definition at line 59 of file rc80211_minstrel\&.h\&.
.SS "unsigned int rate_avg"

.PP
Definition at line 44 of file rc80211_minstrel\&.h\&.
.SS "unsigned int sample_column"

.PP
Definition at line 56 of file rc80211_minstrel\&.h\&.
.SS "unsigned int sample_count"

.PP
Definition at line 52 of file rc80211_minstrel\&.h\&.
.SS "int sample_deferred"

.PP
Definition at line 53 of file rc80211_minstrel\&.h\&.
.SS "unsigned int sample_idx"

.PP
Definition at line 55 of file rc80211_minstrel\&.h\&.
.SS "u8* sample_table"

.PP
Definition at line 63 of file rc80211_minstrel\&.h\&.
.SS "unsigned int sp_ack_dur"

.PP
Definition at line 43 of file rc80211_minstrel\&.h\&.
.SS "unsigned long stats_update"

.PP
Definition at line 42 of file rc80211_minstrel\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for net_mac80211 from the source code\&.
