.TH "/home/guille/msm/net/mac80211/mlme.c" 3 "Sun Jun 1 2014" "Version 1.0" "net_mac80211" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/guille/msm/net/mac80211/mlme.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <linux/delay\&.h>\fP
.br
\fC#include <linux/if_ether\&.h>\fP
.br
\fC#include <linux/skbuff\&.h>\fP
.br
\fC#include <linux/if_arp\&.h>\fP
.br
\fC#include <linux/etherdevice\&.h>\fP
.br
\fC#include <linux/moduleparam\&.h>\fP
.br
\fC#include <linux/rtnetlink\&.h>\fP
.br
\fC#include <linux/pm_qos\&.h>\fP
.br
\fC#include <linux/crc32\&.h>\fP
.br
\fC#include <linux/slab\&.h>\fP
.br
\fC#include <linux/export\&.h>\fP
.br
\fC#include <net/mac80211\&.h>\fP
.br
\fC#include <asm/unaligned\&.h>\fP
.br
\fC#include 'ieee80211_i\&.h'\fP
.br
\fC#include 'driver-ops\&.h'\fP
.br
\fC#include 'rate\&.h'\fP
.br
\fC#include 'led\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIEEE80211_AUTH_TIMEOUT\fP   (HZ / 5)"
.br
.ti -1c
.RI "#define \fBIEEE80211_AUTH_MAX_TRIES\fP   3"
.br
.ti -1c
.RI "#define \fBIEEE80211_AUTH_WAIT_ASSOC\fP   (HZ * 5)"
.br
.ti -1c
.RI "#define \fBIEEE80211_ASSOC_TIMEOUT\fP   (HZ / 5)"
.br
.ti -1c
.RI "#define \fBIEEE80211_ASSOC_MAX_TRIES\fP   3"
.br
.ti -1c
.RI "#define \fBIEEE80211_BEACON_LOSS_COUNT\fP   7"
.br
.ti -1c
.RI "#define \fBIEEE80211_CONNECTION_IDLE_TIME\fP   (30 * HZ)"
.br
.ti -1c
.RI "#define \fBIEEE80211_SIGNAL_AVE_WEIGHT\fP   3"
.br
.ti -1c
.RI "#define \fBIEEE80211_SIGNAL_AVE_MIN_COUNT\fP   4"
.br
.ti -1c
.RI "#define \fBTMR_RUNNING_TIMER\fP   0"
.br
.ti -1c
.RI "#define \fBTMR_RUNNING_CHANSW\fP   1"
.br
.ti -1c
.RI "#define \fBDEAUTH_DISASSOC_LEN\fP   (24 /* hdr */ + 2 /* reason */)"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBrx_mgmt_action\fP { \fBRX_MGMT_NONE\fP, \fBRX_MGMT_CFG80211_DEAUTH\fP, \fBRX_MGMT_CFG80211_DISASSOC\fP, \fBRX_MGMT_CFG80211_RX_AUTH\fP, \fBRX_MGMT_CFG80211_RX_ASSOC\fP, \fBRX_MGMT_CFG80211_ASSOC_TIMEOUT\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmodule_param\fP (max_nullfunc_tries, int, 0644)"
.br
.ti -1c
.RI "\fBMODULE_PARM_DESC\fP (max_nullfunc_tries,'Maximum nullfunc tx tries before disconnecting (reason 4)\&.')"
.br
.ti -1c
.RI "\fBmodule_param\fP (max_probe_tries, int, 0644)"
.br
.ti -1c
.RI "\fBMODULE_PARM_DESC\fP (max_probe_tries,'Maximum probe tries before disconnecting (reason 4)\&.')"
.br
.ti -1c
.RI "\fBmodule_param\fP (probe_wait_ms, int, 0644)"
.br
.ti -1c
.RI "\fBMODULE_PARM_DESC\fP (probe_wait_ms,'Maximum time(ms) to wait for probe response'' before disconnecting (reason 4)\&.')"
.br
.ti -1c
.RI "void \fBieee80211_sta_reset_beacon_monitor\fP (struct \fBieee80211_sub_if_data\fP *sdata)"
.br
.ti -1c
.RI "void \fBieee80211_sta_reset_conn_monitor\fP (struct \fBieee80211_sub_if_data\fP *sdata)"
.br
.ti -1c
.RI "void \fBieee80211_send_pspoll\fP (struct \fBieee80211_local\fP *local, struct \fBieee80211_sub_if_data\fP *sdata)"
.br
.ti -1c
.RI "void \fBieee80211_send_nullfunc\fP (struct \fBieee80211_local\fP *local, struct \fBieee80211_sub_if_data\fP *sdata, int powersave)"
.br
.ti -1c
.RI "void \fBieee80211_chswitch_done\fP (struct ieee80211_vif *vif, bool success)"
.br
.ti -1c
.RI "\fBEXPORT_SYMBOL\fP (\fBieee80211_chswitch_done\fP)"
.br
.ti -1c
.RI "void \fBieee80211_sta_process_chanswitch\fP (struct \fBieee80211_sub_if_data\fP *sdata, struct ieee80211_channel_sw_ie *sw_elem, struct \fBieee80211_bss\fP *bss, u64 timestamp)"
.br
.ti -1c
.RI "void \fBieee80211_enable_dyn_ps\fP (struct ieee80211_vif *vif)"
.br
.ti -1c
.RI "\fBEXPORT_SYMBOL\fP (\fBieee80211_enable_dyn_ps\fP)"
.br
.ti -1c
.RI "void \fBieee80211_disable_dyn_ps\fP (struct ieee80211_vif *vif)"
.br
.ti -1c
.RI "\fBEXPORT_SYMBOL\fP (\fBieee80211_disable_dyn_ps\fP)"
.br
.ti -1c
.RI "void \fBieee80211_recalc_ps\fP (struct \fBieee80211_local\fP *local, s32 latency)"
.br
.ti -1c
.RI "void \fBieee80211_dynamic_ps_disable_work\fP (struct work_struct *work)"
.br
.ti -1c
.RI "void \fBieee80211_dynamic_ps_enable_work\fP (struct work_struct *work)"
.br
.ti -1c
.RI "void \fBieee80211_dynamic_ps_timer\fP (unsigned long data)"
.br
.ti -1c
.RI "void \fBieee80211_sta_rx_notify\fP (struct \fBieee80211_sub_if_data\fP *sdata, struct ieee80211_hdr *hdr)"
.br
.ti -1c
.RI "void \fBieee80211_sta_tx_notify\fP (struct \fBieee80211_sub_if_data\fP *sdata, struct ieee80211_hdr *hdr, bool ack)"
.br
.ti -1c
.RI "struct sk_buff * \fBieee80211_ap_probereq_get\fP (struct ieee80211_hw *hw, struct ieee80211_vif *vif)"
.br
.ti -1c
.RI "\fBEXPORT_SYMBOL\fP (\fBieee80211_ap_probereq_get\fP)"
.br
.ti -1c
.RI "void \fBieee80211_beacon_connection_loss_work\fP (struct work_struct *work)"
.br
.ti -1c
.RI "void \fBieee80211_beacon_loss\fP (struct ieee80211_vif *vif)"
.br
.ti -1c
.RI "\fBEXPORT_SYMBOL\fP (\fBieee80211_beacon_loss\fP)"
.br
.ti -1c
.RI "void \fBieee80211_connection_loss\fP (struct ieee80211_vif *vif)"
.br
.ti -1c
.RI "\fBEXPORT_SYMBOL\fP (\fBieee80211_connection_loss\fP)"
.br
.ti -1c
.RI "void \fBieee80211_sta_rx_queued_mgmt\fP (struct \fBieee80211_sub_if_data\fP *sdata, struct sk_buff *skb)"
.br
.ti -1c
.RI "void \fBieee80211_sta_work\fP (struct \fBieee80211_sub_if_data\fP *sdata)"
.br
.ti -1c
.RI "void \fBieee80211_sta_setup_sdata\fP (struct \fBieee80211_sub_if_data\fP *sdata)"
.br
.ti -1c
.RI "void \fBieee80211_mlme_notify_scan_completed\fP (struct \fBieee80211_local\fP *local)"
.br
.ti -1c
.RI "int \fBieee80211_max_network_latency\fP (struct notifier_block *nb, unsigned long data, void *dummy)"
.br
.ti -1c
.RI "int \fBieee80211_mgd_auth\fP (struct \fBieee80211_sub_if_data\fP *sdata, struct cfg80211_auth_request *req)"
.br
.ti -1c
.RI "int \fBieee80211_mgd_assoc\fP (struct \fBieee80211_sub_if_data\fP *sdata, struct cfg80211_assoc_request *req)"
.br
.ti -1c
.RI "int \fBieee80211_mgd_deauth\fP (struct \fBieee80211_sub_if_data\fP *sdata, struct cfg80211_deauth_request *req)"
.br
.ti -1c
.RI "int \fBieee80211_mgd_disassoc\fP (struct \fBieee80211_sub_if_data\fP *sdata, struct cfg80211_disassoc_request *req)"
.br
.ti -1c
.RI "void \fBieee80211_mgd_stop\fP (struct \fBieee80211_sub_if_data\fP *sdata)"
.br
.ti -1c
.RI "void \fBieee80211_cqm_rssi_notify\fP (struct ieee80211_vif *vif, enum nl80211_cqm_rssi_threshold_event rssi_event, gfp_t gfp)"
.br
.ti -1c
.RI "\fBEXPORT_SYMBOL\fP (\fBieee80211_cqm_rssi_notify\fP)"
.br
.ti -1c
.RI "unsigned char \fBieee80211_get_operstate\fP (struct ieee80211_vif *vif)"
.br
.ti -1c
.RI "\fBEXPORT_SYMBOL\fP (\fBieee80211_get_operstate\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DEAUTH_DISASSOC_LEN   (24 /* hdr */ + 2 /* reason */)"

.PP
Definition at line 91 of file mlme\&.c\&.
.SS "#define IEEE80211_ASSOC_MAX_TRIES   3"

.PP
Definition at line 37 of file mlme\&.c\&.
.SS "#define IEEE80211_ASSOC_TIMEOUT   (HZ / 5)"

.PP
Definition at line 36 of file mlme\&.c\&.
.SS "#define IEEE80211_AUTH_MAX_TRIES   3"

.PP
Definition at line 34 of file mlme\&.c\&.
.SS "#define IEEE80211_AUTH_TIMEOUT   (HZ / 5)"

.PP
Definition at line 33 of file mlme\&.c\&.
.SS "#define IEEE80211_AUTH_WAIT_ASSOC   (HZ * 5)"

.PP
Definition at line 35 of file mlme\&.c\&.
.SS "#define IEEE80211_BEACON_LOSS_COUNT   7"

.PP
Definition at line 57 of file mlme\&.c\&.
.SS "#define IEEE80211_CONNECTION_IDLE_TIME   (30 * HZ)"

.PP
Definition at line 63 of file mlme\&.c\&.
.SS "#define IEEE80211_SIGNAL_AVE_MIN_COUNT   4"

.PP
Definition at line 86 of file mlme\&.c\&.
.SS "#define IEEE80211_SIGNAL_AVE_WEIGHT   3"

.PP
Definition at line 80 of file mlme\&.c\&.
.SS "#define TMR_RUNNING_CHANSW   1"

.PP
Definition at line 89 of file mlme\&.c\&.
.SS "#define TMR_RUNNING_TIMER   0"

.PP
Definition at line 88 of file mlme\&.c\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBrx_mgmt_action\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIRX_MGMT_NONE \fP\fP
.TP
\fB\fIRX_MGMT_CFG80211_DEAUTH \fP\fP
.TP
\fB\fIRX_MGMT_CFG80211_DISASSOC \fP\fP
.TP
\fB\fIRX_MGMT_CFG80211_RX_AUTH \fP\fP
.TP
\fB\fIRX_MGMT_CFG80211_RX_ASSOC \fP\fP
.TP
\fB\fIRX_MGMT_CFG80211_ASSOC_TIMEOUT \fP\fP
.PP
Definition at line 99 of file mlme\&.c\&.
.SH "Function Documentation"
.PP 
.SS "EXPORT_SYMBOL (\fBieee80211_chswitch_done\fP)"

.SS "EXPORT_SYMBOL (\fBieee80211_enable_dyn_ps\fP)"

.SS "EXPORT_SYMBOL (\fBieee80211_disable_dyn_ps\fP)"

.SS "EXPORT_SYMBOL (\fBieee80211_ap_probereq_get\fP)"

.SS "EXPORT_SYMBOL (\fBieee80211_beacon_loss\fP)"

.SS "EXPORT_SYMBOL (\fBieee80211_connection_loss\fP)"

.SS "EXPORT_SYMBOL (\fBieee80211_cqm_rssi_notify\fP)"

.SS "EXPORT_SYMBOL (\fBieee80211_get_operstate\fP)"

.SS "struct sk_buff* ieee80211_ap_probereq_get (struct ieee80211_hw *hw, struct ieee80211_vif *vif)"

.PP
Definition at line 1663 of file mlme\&.c\&.
.SS "void ieee80211_beacon_connection_loss_work (struct work_struct *work)"

.PP
Definition at line 1722 of file mlme\&.c\&.
.SS "void ieee80211_beacon_loss (struct ieee80211_vif *vif)"

.PP
Definition at line 1744 of file mlme\&.c\&.
.SS "void ieee80211_chswitch_done (struct ieee80211_vif *vif, boolsuccess)"

.PP
Definition at line 773 of file mlme\&.c\&.
.SS "void ieee80211_connection_loss (struct ieee80211_vif *vif)"

.PP
Definition at line 1756 of file mlme\&.c\&.
.SS "void ieee80211_cqm_rssi_notify (struct ieee80211_vif *vif, enum nl80211_cqm_rssi_threshold_eventrssi_event, gfp_tgfp)"

.PP
Definition at line 3553 of file mlme\&.c\&.
.SS "void ieee80211_disable_dyn_ps (struct ieee80211_vif *vif)"

.PP
Definition at line 909 of file mlme\&.c\&.
.SS "void ieee80211_dynamic_ps_disable_work (struct work_struct *work)"

.PP
Definition at line 1095 of file mlme\&.c\&.
.SS "void ieee80211_dynamic_ps_enable_work (struct work_struct *work)"

.PP
Definition at line 1110 of file mlme\&.c\&.
.SS "void ieee80211_dynamic_ps_timer (unsigned longdata)"

.PP
Definition at line 1185 of file mlme\&.c\&.
.SS "void ieee80211_enable_dyn_ps (struct ieee80211_vif *vif)"

.PP
Definition at line 894 of file mlme\&.c\&.
.SS "unsigned char ieee80211_get_operstate (struct ieee80211_vif *vif)"

.PP
Definition at line 3565 of file mlme\&.c\&.
.SS "int ieee80211_max_network_latency (struct notifier_block *nb, unsigned longdata, void *dummy)"

.PP
Definition at line 3063 of file mlme\&.c\&.
.SS "int ieee80211_mgd_assoc (struct \fBieee80211_sub_if_data\fP *sdata, struct cfg80211_assoc_request *req)"

.PP
Definition at line 3270 of file mlme\&.c\&.
.SS "int ieee80211_mgd_auth (struct \fBieee80211_sub_if_data\fP *sdata, struct cfg80211_auth_request *req)"

.PP
Definition at line 3174 of file mlme\&.c\&.
.SS "int ieee80211_mgd_deauth (struct \fBieee80211_sub_if_data\fP *sdata, struct cfg80211_deauth_request *req)"

.PP
Definition at line 3464 of file mlme\&.c\&.
.SS "int ieee80211_mgd_disassoc (struct \fBieee80211_sub_if_data\fP *sdata, struct cfg80211_disassoc_request *req)"

.PP
Definition at line 3502 of file mlme\&.c\&.
.SS "void ieee80211_mgd_stop (struct \fBieee80211_sub_if_data\fP *sdata)"

.PP
Definition at line 3540 of file mlme\&.c\&.
.SS "void ieee80211_mlme_notify_scan_completed (struct \fBieee80211_local\fP *local)"

.PP
Definition at line 3052 of file mlme\&.c\&.
.SS "void ieee80211_recalc_ps (struct \fBieee80211_local\fP *local, s32latency)"

.PP
Definition at line 1003 of file mlme\&.c\&.
.SS "void ieee80211_send_nullfunc (struct \fBieee80211_local\fP *local, struct \fBieee80211_sub_if_data\fP *sdata, intpowersave)"

.PP
Definition at line 685 of file mlme\&.c\&.
.SS "void ieee80211_send_pspoll (struct \fBieee80211_local\fP *local, struct \fBieee80211_sub_if_data\fP *sdata)"

.PP
Definition at line 668 of file mlme\&.c\&.
.SS "void ieee80211_sta_process_chanswitch (struct \fBieee80211_sub_if_data\fP *sdata, struct ieee80211_channel_sw_ie *sw_elem, struct \fBieee80211_bss\fP *bss, u64timestamp)"

.PP
Definition at line 810 of file mlme\&.c\&.
.SS "void ieee80211_sta_reset_beacon_monitor (struct \fBieee80211_sub_if_data\fP *sdata)"

.PP
Definition at line 144 of file mlme\&.c\&.
.SS "void ieee80211_sta_reset_conn_monitor (struct \fBieee80211_sub_if_data\fP *sdata)"

.PP
Definition at line 153 of file mlme\&.c\&.
.SS "void ieee80211_sta_rx_notify (struct \fBieee80211_sub_if_data\fP *sdata, struct ieee80211_hdr *hdr)"

.PP
Definition at line 1503 of file mlme\&.c\&.
.SS "void ieee80211_sta_rx_queued_mgmt (struct \fBieee80211_sub_if_data\fP *sdata, struct sk_buff *skb)"

.PP
Definition at line 2571 of file mlme\&.c\&.
.SS "void ieee80211_sta_setup_sdata (struct \fBieee80211_sub_if_data\fP *sdata)"

.PP
Definition at line 3019 of file mlme\&.c\&.
.SS "void ieee80211_sta_tx_notify (struct \fBieee80211_sub_if_data\fP *sdata, struct ieee80211_hdr *hdr, boolack)"

.PP
Definition at line 1549 of file mlme\&.c\&.
.SS "void ieee80211_sta_work (struct \fBieee80211_sub_if_data\fP *sdata)"

.PP
Definition at line 2777 of file mlme\&.c\&.
.SS "module_param (max_nullfunc_tries, int, 0644)"

.SS "module_param (max_probe_tries, int, 0644)"

.SS "module_param (probe_wait_ms, int, 0644)"

.SS "MODULE_PARM_DESC (max_nullfunc_tries, 'Maximum nullfunc tx tries before disconnecting (reason 4)\&.')"

.SS "MODULE_PARM_DESC (max_probe_tries, 'Maximum probe tries before disconnecting (reason 4)\&.')"

.SS "MODULE_PARM_DESC (probe_wait_ms, 'Maximum time(ms) to wait for probe response'' before disconnecting (reason 4)\&.')"

.SH "Author"
.PP 
Generated automatically by Doxygen for net_mac80211 from the source code\&.
