.TH "mpath_node" 3 "Sun Jun 1 2014" "Version 1.0" "net_mac80211" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mpath_node \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct hlist_node \fBlist\fP"
.br
.ti -1c
.RI "struct rcu_head \fBrcu\fP"
.br
.ti -1c
.RI "struct \fBmesh_path\fP * \fBmpath\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 37 of file mesh_pathtbl\&.c\&.
.SH "Field Documentation"
.PP 
.SS "struct hlist_node list"

.PP
Definition at line 38 of file mesh_pathtbl\&.c\&.
.SS "struct \fBmesh_path\fP* mpath"

.PP
Definition at line 43 of file mesh_pathtbl\&.c\&.
.SS "struct rcu_head rcu"

.PP
Definition at line 39 of file mesh_pathtbl\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for net_mac80211 from the source code\&.
