.TH "rate_control_alg" 3 "Sun Jun 1 2014" "Version 1.0" "net_mac80211" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rate_control_alg \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct list_head \fBlist\fP"
.br
.ti -1c
.RI "struct rate_control_ops * \fBops\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file rate\&.c\&.
.SH "Field Documentation"
.PP 
.SS "struct list_head list"

.PP
Definition at line 20 of file rate\&.c\&.
.SS "struct rate_control_ops* ops"

.PP
Definition at line 21 of file rate\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for net_mac80211 from the source code\&.
