.TH "/home/guille/msm/net/mac80211/rc80211_minstrel_ht.h" 3 "Sun Jun 1 2014" "Version 1.0" "net_mac80211" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/guille/msm/net/mac80211/rc80211_minstrel_ht.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBmcs_group\fP"
.br
.ti -1c
.RI "struct \fBminstrel_rate_stats\fP"
.br
.ti -1c
.RI "struct \fBminstrel_mcs_group_data\fP"
.br
.ti -1c
.RI "struct \fBminstrel_ht_sta\fP"
.br
.ti -1c
.RI "struct \fBminstrel_ht_sta_priv\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMINSTREL_MAX_STREAMS\fP   3"
.br
.ti -1c
.RI "#define \fBMINSTREL_STREAM_GROUPS\fP   4"
.br
.ti -1c
.RI "#define \fBMINSTREL_SCALE\fP   16"
.br
.ti -1c
.RI "#define \fBMINSTREL_FRAC\fP(val, div)   (((val) << \fBMINSTREL_SCALE\fP) / div)"
.br
.ti -1c
.RI "#define \fBMINSTREL_TRUNC\fP(val)   ((val) >> \fBMINSTREL_SCALE\fP)"
.br
.ti -1c
.RI "#define \fBMCS_GROUP_RATES\fP   8"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBminstrel_ht_add_sta_debugfs\fP (void *priv, void *priv_sta, struct dentry *dir)"
.br
.ti -1c
.RI "void \fBminstrel_ht_remove_sta_debugfs\fP (void *priv, void *priv_sta)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBmcs_group\fP \fBminstrel_mcs_groups\fP []"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MCS_GROUP_RATES   8"

.PP
Definition at line 24 of file rc80211_minstrel_ht\&.h\&.
.SS "#define MINSTREL_FRAC(val, div)   (((val) << \fBMINSTREL_SCALE\fP) / div)"

.PP
Definition at line 21 of file rc80211_minstrel_ht\&.h\&.
.SS "#define MINSTREL_MAX_STREAMS   3"

.PP
Definition at line 16 of file rc80211_minstrel_ht\&.h\&.
.SS "#define MINSTREL_SCALE   16"

.PP
Definition at line 20 of file rc80211_minstrel_ht\&.h\&.
.SS "#define MINSTREL_STREAM_GROUPS   4"

.PP
Definition at line 17 of file rc80211_minstrel_ht\&.h\&.
.SS "#define MINSTREL_TRUNC(val)   ((val) >> \fBMINSTREL_SCALE\fP)"

.PP
Definition at line 22 of file rc80211_minstrel_ht\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void minstrel_ht_add_sta_debugfs (void *priv, void *priv_sta, struct dentry *dir)"

.PP
Definition at line 106 of file rc80211_minstrel_ht_debugfs\&.c\&.
.SS "void minstrel_ht_remove_sta_debugfs (void *priv, void *priv_sta)"

.PP
Definition at line 115 of file rc80211_minstrel_ht_debugfs\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "struct \fBmcs_group\fP minstrel_mcs_groups[]"

.PP
Definition at line 74 of file rc80211_minstrel_ht\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for net_mac80211 from the source code\&.
