.TH "/home/guille/msm/net/mac80211/rc80211_pid_algo.c" 3 "Sun Jun 1 2014" "Version 1.0" "net_mac80211" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/guille/msm/net/mac80211/rc80211_pid_algo.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <linux/netdevice\&.h>\fP
.br
\fC#include <linux/types\&.h>\fP
.br
\fC#include <linux/skbuff\&.h>\fP
.br
\fC#include <linux/debugfs\&.h>\fP
.br
\fC#include <linux/slab\&.h>\fP
.br
\fC#include <net/mac80211\&.h>\fP
.br
\fC#include 'rate\&.h'\fP
.br
\fC#include 'mesh\&.h'\fP
.br
\fC#include 'rc80211_pid\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int __init \fBrc80211_pid_init\fP (void)"
.br
.ti -1c
.RI "void \fBrc80211_pid_exit\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void rc80211_pid_exit (void)"

.PP
Definition at line 474 of file rc80211_pid_algo\&.c\&.
.SS "int __init rc80211_pid_init (void)"

.PP
Definition at line 469 of file rc80211_pid_algo\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for net_mac80211 from the source code\&.
