.TH "rc_pid_event" 3 "Sun Jun 1 2014" "Version 1.0" "net_mac80211" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rc_pid_event \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rc80211_pid\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned long \fBtimestamp\fP"
.br
.ti -1c
.RI "unsigned int \fBid\fP"
.br
.ti -1c
.RI "enum \fBrc_pid_event_type\fP \fBtype\fP"
.br
.ti -1c
.RI "union \fBrc_pid_event_data\fP \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 79 of file rc80211_pid\&.h\&.
.SH "Field Documentation"
.PP 
.SS "union \fBrc_pid_event_data\fP data"

.PP
Definition at line 90 of file rc80211_pid\&.h\&.
.SS "unsigned int id"

.PP
Definition at line 84 of file rc80211_pid\&.h\&.
.SS "unsigned long timestamp"

.PP
Definition at line 81 of file rc80211_pid\&.h\&.
.SS "enum \fBrc_pid_event_type\fP type"

.PP
Definition at line 87 of file rc80211_pid\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for net_mac80211 from the source code\&.
