.TH "rc_pid_rateinfo" 3 "Sun Jun 1 2014" "Version 1.0" "net_mac80211" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rc_pid_rateinfo \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rc80211_pid\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBindex\fP"
.br
.ti -1c
.RI "int \fBrev_index\fP"
.br
.ti -1c
.RI "bool \fBvalid\fP"
.br
.ti -1c
.RI "int \fBdiff\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 228 of file rc80211_pid\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int diff"

.PP
Definition at line 240 of file rc80211_pid\&.h\&.
.SS "int index"

.PP
Definition at line 231 of file rc80211_pid\&.h\&.
.SS "int rev_index"

.PP
Definition at line 234 of file rc80211_pid\&.h\&.
.SS "bool valid"

.PP
Definition at line 237 of file rc80211_pid\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for net_mac80211 from the source code\&.
