.TH "rc_pid_sta_info" 3 "Sun Jun 1 2014" "Version 1.0" "net_mac80211" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rc_pid_sta_info \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rc80211_pid\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned long \fBlast_change\fP"
.br
.ti -1c
.RI "unsigned long \fBlast_sample\fP"
.br
.ti -1c
.RI "u32 \fBtx_num_failed\fP"
.br
.ti -1c
.RI "u32 \fBtx_num_xmit\fP"
.br
.ti -1c
.RI "int \fBtxrate_idx\fP"
.br
.ti -1c
.RI "s32 \fBerr_avg_sc\fP"
.br
.ti -1c
.RI "u32 \fBlast_pf\fP"
.br
.ti -1c
.RI "u8 \fBsharp_cnt\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 172 of file rc80211_pid\&.h\&.
.SH "Field Documentation"
.PP 
.SS "s32 err_avg_sc"

.PP
Definition at line 208 of file rc80211_pid\&.h\&.
.SS "unsigned long last_change"

.PP
Definition at line 173 of file rc80211_pid\&.h\&.
.SS "u32 last_pf"

.PP
Definition at line 211 of file rc80211_pid\&.h\&.
.SS "unsigned long last_sample"

.PP
Definition at line 174 of file rc80211_pid\&.h\&.
.SS "u8 sharp_cnt"

.PP
Definition at line 214 of file rc80211_pid\&.h\&.
.SS "u32 tx_num_failed"

.PP
Definition at line 176 of file rc80211_pid\&.h\&.
.SS "u32 tx_num_xmit"

.PP
Definition at line 177 of file rc80211_pid\&.h\&.
.SS "int txrate_idx"

.PP
Definition at line 179 of file rc80211_pid\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for net_mac80211 from the source code\&.
