.TH "rc_pid_events_file_info" 3 "Sun Jun 1 2014" "Version 1.0" "net_mac80211" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rc_pid_events_file_info \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rc80211_pid\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBrc_pid_event_buffer\fP * \fBevents\fP"
.br
.ti -1c
.RI "unsigned int \fBnext_entry\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 113 of file rc80211_pid\&.h\&.
.SH "Field Documentation"
.PP 
.SS "struct \fBrc_pid_event_buffer\fP* events"

.PP
Definition at line 115 of file rc80211_pid\&.h\&.
.SS "unsigned int next_entry"

.PP
Definition at line 118 of file rc80211_pid\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for net_mac80211 from the source code\&.
