.TH "rc_pid_info" 3 "Sun Jun 1 2014" "Version 1.0" "net_mac80211" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rc_pid_info \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rc80211_pid\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBtarget\fP"
.br
.ti -1c
.RI "unsigned int \fBsampling_period\fP"
.br
.ti -1c
.RI "int \fBcoeff_p\fP"
.br
.ti -1c
.RI "int \fBcoeff_i\fP"
.br
.ti -1c
.RI "int \fBcoeff_d\fP"
.br
.ti -1c
.RI "unsigned int \fBsmoothing_shift\fP"
.br
.ti -1c
.RI "unsigned int \fBsharpen_factor\fP"
.br
.ti -1c
.RI "unsigned int \fBsharpen_duration\fP"
.br
.ti -1c
.RI "unsigned int \fBnorm_offset\fP"
.br
.ti -1c
.RI "struct \fBrc_pid_rateinfo\fP * \fBrinfo\fP"
.br
.ti -1c
.RI "int \fBoldrate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 243 of file rc80211_pid\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int coeff_d"

.PP
Definition at line 254 of file rc80211_pid\&.h\&.
.SS "int coeff_i"

.PP
Definition at line 253 of file rc80211_pid\&.h\&.
.SS "int coeff_p"

.PP
Definition at line 252 of file rc80211_pid\&.h\&.
.SS "unsigned int norm_offset"

.PP
Definition at line 264 of file rc80211_pid\&.h\&.
.SS "int oldrate"

.PP
Definition at line 270 of file rc80211_pid\&.h\&.
.SS "struct \fBrc_pid_rateinfo\fP* rinfo"

.PP
Definition at line 267 of file rc80211_pid\&.h\&.
.SS "unsigned int sampling_period"

.PP
Definition at line 249 of file rc80211_pid\&.h\&.
.SS "unsigned int sharpen_duration"

.PP
Definition at line 261 of file rc80211_pid\&.h\&.
.SS "unsigned int sharpen_factor"

.PP
Definition at line 260 of file rc80211_pid\&.h\&.
.SS "unsigned int smoothing_shift"

.PP
Definition at line 257 of file rc80211_pid\&.h\&.
.SS "unsigned int target"

.PP
Definition at line 246 of file rc80211_pid\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for net_mac80211 from the source code\&.
