.TH "tid_ampdu_tx" 3 "Sun Jun 1 2014" "Version 1.0" "net_mac80211" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tid_ampdu_tx \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sta_info\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct rcu_head \fBrcu_head\fP"
.br
.ti -1c
.RI "struct timer_list \fBsession_timer\fP"
.br
.ti -1c
.RI "struct timer_list \fBaddba_resp_timer\fP"
.br
.ti -1c
.RI "struct sk_buff_head \fBpending\fP"
.br
.ti -1c
.RI "unsigned long \fBstate\fP"
.br
.ti -1c
.RI "u16 \fBtimeout\fP"
.br
.ti -1c
.RI "u8 \fBdialog_token\fP"
.br
.ti -1c
.RI "u8 \fBstop_initiator\fP"
.br
.ti -1c
.RI "bool \fBtx_stop\fP"
.br
.ti -1c
.RI "u8 \fBbuf_size\fP"
.br
.ti -1c
.RI "u16 \fBfailed_bar_ssn\fP"
.br
.ti -1c
.RI "bool \fBbar_pending\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
struct \fBtid_ampdu_tx\fP - TID aggregation information (Tx)\&.
.PP
: rcu head for freeing structure : check if we keep Tx-ing on the TID (by timeout value) : timer for peer's response to addba request : pending frames queue -- use sta's spinlock to protect : dialog token for aggregation session : session timeout value to be filled in ADDBA requests : session state (see above) : initiator of a session stop : TX DelBA frame when stopping : reorder buffer size at receiver : ssn of the last failed BAR tx attempt : BAR needs to be re-sent
.PP
This structure's lifetime is managed by RCU, assignments to the array holding it must hold the aggregation mutex\&.
.PP
The TX path can access it under RCU lock-free if, and only if, the state has the flag HT_AGG_STATE_OPERATIONAL set\&. Otherwise, the TX path must also acquire the spinlock and re-check the state, see comments in the tx code touching it\&. 
.PP
Definition at line 119 of file sta_info\&.h\&.
.SH "Field Documentation"
.PP 
.SS "struct timer_list addba_resp_timer"

.PP
Definition at line 122 of file sta_info\&.h\&.
.SS "bool bar_pending"

.PP
Definition at line 132 of file sta_info\&.h\&.
.SS "u8 buf_size"

.PP
Definition at line 129 of file sta_info\&.h\&.
.SS "u8 dialog_token"

.PP
Definition at line 126 of file sta_info\&.h\&.
.SS "u16 failed_bar_ssn"

.PP
Definition at line 131 of file sta_info\&.h\&.
.SS "struct sk_buff_head pending"

.PP
Definition at line 123 of file sta_info\&.h\&.
.SS "struct rcu_head rcu_head"

.PP
Definition at line 120 of file sta_info\&.h\&.
.SS "struct timer_list session_timer"

.PP
Definition at line 121 of file sta_info\&.h\&.
.SS "unsigned long state"

.PP
Definition at line 124 of file sta_info\&.h\&.
.SS "u8 stop_initiator"

.PP
Definition at line 127 of file sta_info\&.h\&.
.SS "u16 timeout"

.PP
Definition at line 125 of file sta_info\&.h\&.
.SS "bool tx_stop"

.PP
Definition at line 128 of file sta_info\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for net_mac80211 from the source code\&.
