.TH "tid_ampdu_rx" 3 "Sun Jun 1 2014" "Version 1.0" "net_mac80211" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tid_ampdu_rx \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sta_info\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct rcu_head \fBrcu_head\fP"
.br
.ti -1c
.RI "spinlock_t \fBreorder_lock\fP"
.br
.ti -1c
.RI "struct sk_buff ** \fBreorder_buf\fP"
.br
.ti -1c
.RI "unsigned long * \fBreorder_time\fP"
.br
.ti -1c
.RI "struct timer_list \fBsession_timer\fP"
.br
.ti -1c
.RI "struct timer_list \fBreorder_timer\fP"
.br
.ti -1c
.RI "u16 \fBhead_seq_num\fP"
.br
.ti -1c
.RI "u16 \fBstored_mpdu_num\fP"
.br
.ti -1c
.RI "u16 \fBssn\fP"
.br
.ti -1c
.RI "u16 \fBbuf_size\fP"
.br
.ti -1c
.RI "u16 \fBtimeout\fP"
.br
.ti -1c
.RI "u8 \fBdialog_token\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
struct \fBtid_ampdu_rx\fP - TID aggregation information (Rx)\&.
.PP
: buffer to reorder incoming aggregated MPDUs : jiffies when skb was added : check if peer keeps Tx-ing on the TID (by timeout value) : releases expired frames from the reorder buffer\&. : head sequence number in reordering buffer\&. : number of MPDUs in reordering buffer : Starting Sequence Number expected to be aggregated\&. : buffer size for incoming A-MPDUs : reset timer value (in TUs)\&. : dialog token for aggregation session : RCU head used for freeing this struct : serializes access to reorder buffer, see below\&.
.PP
This structure's lifetime is managed by RCU, assignments to the array holding it must hold the aggregation mutex\&.
.PP
The  is used to protect the members of this struct, except for ,  and , which are constant across the lifetime of the struct (the dialog token being used only for debugging)\&. 
.PP
Definition at line 159 of file sta_info\&.h\&.
.SH "Field Documentation"
.PP 
.SS "u16 buf_size"

.PP
Definition at line 169 of file sta_info\&.h\&.
.SS "u8 dialog_token"

.PP
Definition at line 171 of file sta_info\&.h\&.
.SS "u16 head_seq_num"

.PP
Definition at line 166 of file sta_info\&.h\&.
.SS "struct rcu_head rcu_head"

.PP
Definition at line 160 of file sta_info\&.h\&.
.SS "struct sk_buff** reorder_buf"

.PP
Definition at line 162 of file sta_info\&.h\&.
.SS "spinlock_t reorder_lock"

.PP
Definition at line 161 of file sta_info\&.h\&.
.SS "unsigned long* reorder_time"

.PP
Definition at line 163 of file sta_info\&.h\&.
.SS "struct timer_list reorder_timer"

.PP
Definition at line 165 of file sta_info\&.h\&.
.SS "struct timer_list session_timer"

.PP
Definition at line 164 of file sta_info\&.h\&.
.SS "u16 ssn"

.PP
Definition at line 168 of file sta_info\&.h\&.
.SS "u16 stored_mpdu_num"

.PP
Definition at line 167 of file sta_info\&.h\&.
.SS "u16 timeout"

.PP
Definition at line 170 of file sta_info\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for net_mac80211 from the source code\&.
